### ISSUE TITLE
build 错误

### ISSUE THREAD

**Issue by liting-yes** [JasKang/vite-plugin-markdown-preview#36]
<img width="1055" alt="Screenshot 2023-02-07 at 22 15 20" src="https://user-images.githubusercontent.com/69500429/217269978-0f327baf-a0f1-40fd-895d-0a6c7e8a92d7.png">

我知道应该是我的问题，但是我实在是一下子没找到问题所在，请教一下

`pnpm build` 失败，这个线上也不好demo，放一下仓库吧 🤣
仓库地址：https://github.com/liting-yes/css.git

**Comment by liting-yes** [comment]
感觉是不是打包有点问题？但是我还没找到原因
我从 npm 下载的包不行，但是我直接fork这个插件到项目里却可以

**Comment by liting-yes** [comment]
而且在插件仓库的demo就能复现，vitepress demo里把 vite-plugin-markdown-preview 替换成 npm 下载的，就打包报错了

**Comment by tomieric** [comment]
参考[https://github.com/vuejs/vitepress/issues/1465](https://github.com/vuejs/vitepress/issues/1465)

```js
defineConfig({
   vite: {
        plugins: [MarkdownPreview()],
        ssr: {
             noExternal: ['vite-plugin-markdown-preview'],
        },
   }
})
```

这里是编译通过 [https://screen-ui-docs.vercel.app/components/header](https://screen-ui-docs.vercel.app/components/header)

**Comment by shiliangL** [comment]
同上，遇到了一样的问题。按照上面的配置打包还是报错。
![image](https://github.com/JasKang/vite-plugin-markdown-preview/assets/24687496/61803097-5e65-4b1d-818c-d12b8227ef69)

**Comment by tomieric** [comment]
> 你好，请问解决了吗？1.0.4碰到同样的问题

加一下配置可以的

```js
defineConfig({
   vite: {
        plugins: [MarkdownPreview()],
        ssr: {
             noExternal: ['vite-plugin-markdown-preview'],
        },
   }
})
```

**Comment by JasKang** [comment]
1.1.0 fixed it  #42
