### ISSUE TITLE
运行playground\vite代码，解析preview代码块失败

### ISSUE THREAD

**Issue by xiongchaoren** [JasKang/vite-plugin-markdown-preview#37]
运行playground\vite代码，提示"Failed to load url /src/index.md.DemoBlockI0.vue (resolved id: /src/index.md.DemoBlockI0.vue) in D:/xxl/study/vite-plugin-markdown-preview-main/playground/vite/src/index.md. Does the file exist?"

以下是所有依赖项
`
"devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "vite-plugin-markdown-preview": "^1.0.3",
    "vite-plugin-vue-markdown": "^0.22.2",
    "markdown-it-shiki": "^0.7.2"
  },
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "vite"
      ]
    }
  }
`

**Comment by XiaoYang943** [comment]
我也遇到了相同的问题，请问您解决了吗
