### ISSUE TITLE
 vite.config.ts导入MarkdownPreview报错问题

### ISSUE THREAD

**Issue by yang-xianzhu** [JasKang/vite-plugin-markdown-preview#40]
<img width="1057" alt="image" src="https://github.com/JasKang/vite-plugin-markdown-preview/assets/92789120/dfcca843-f2dd-428b-a309-8d318b198736">
项目相关依赖：
<img width="516" alt="image" src="https://github.com/JasKang/vite-plugin-markdown-preview/assets/92789120/b9eeb11d-38a9-480c-8ca2-0540f6662ef2">

**Comment by JasKang** [comment]
package.json 里设置 
"type": "module"
